export const categories = [
    { value: "all", label: "All Types" },
    { value: "image-design", label: "Image Design" },
    { value: "logo-design", label: "Logo Design" },
    { value: "photography", label: "Photography" },
    { value: "article-writing", label: "Article Writing" },
    { value: "story-writing", label: "Story Writing" },
    { value: "poetry-writing", label: "Poetry Writing" },
    { value: "business-idea", label: "Business Idea" },
    { value: "startup-pitch", label: "Startup Pitch" },
    { value: "gaming-review", label: "Gaming Review" },
    { value: "coding-challenge", label: "Coding Challenge" },
    { value: "web-design", label: "Web Design" },
    { value: "video-editing", label: "Video Editing" },
    { value: "meme-creation", label: "Meme Creation" },
    { value: "marketing-strategy", label: "Marketing Strategy" },
    { value: "innovation-challenge", label: "Innovation Challenge" },
    { value: "other", label: "Other" },
];
